### ISSUE TITLE
kama.h does not exist inside include/frp/kama.h

### ISSUE THREAD

**Issue by Joaggi** [dnbaker/frp#2]
When I tried to compile the code with make, after installing all the dependencies I received the following error:

fatal error: frp/kama.h: the file does not exist or directory

**Comment by dnbaker** [comment]
Hi, Joaggi! Thanks for letting me know. There's a file I was working with locally that I apparently failed to push, but no progress really came of it. The project (as of [this commit](https://github.com/dnbaker/frp/commit/515f12a791fbe66f89a2bfa80127a0422cf08466) ) should now build.

**Comment by Joaggi** [comment]
Thanks for your quick response. I just started to read the paper, it seems very interesting. This error is solved, so I closed this thread.
