### ISSUE TITLE
cd py && make inside Makefile

### ISSUE THREAD

**Issue by Joaggi** [dnbaker/frp#5]
Hi Daniel,

I just made a git pull and after tried to perform the make, I received an error with the command 

`cd py && make.`

 It seems that inside py is not a Makefile available.

I tried to remove that line but after doing that the making process stops at that line.

**Comment by dnbaker** [comment]
Hi Joaggi,

I forgot to update the README after changing the installation method to setup.py. I've also added a Makefile which then runs that, so the updated version should install it via make as well.

It should simply be `cd py && python3 setup.py install`,

**Comment by Joaggi** [comment]
Thanks for your quick response 👍 .

Now, it seems that inside py there is not a setup.py file. I received a message "no such file or directory"

**Comment by dnbaker** [comment]
Thanks again, I didn't push that file until [this commit just now](https://github.com/dnbaker/frp/commit/20db6d2d0853eae089cbbc2d0b4d278a5ce7d3b7).
